import img1 from "../../assets/images/BestSeller1.jpg";
import imgAsus from "../../assets/images/asus.jpg";

export const fakeDataBestSeller = [
  {
    id: 1,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
  {
    id: 2,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
  {
    id: 3,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
  {
    id: 4,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
  {
    id: 5,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
  {
    id: 6,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
  {
    id: 7,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
  {
    id: 8,
    image: img1,
    title: "MacBook Air",
    description: "Don’t take it lightly.",
    price: "27,577,000 ₫",
  },
];

export const FakeDataProduct = [
  {
    id: 1,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
  {
    id: 2,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
  {
    id: 3,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
  {
    id: 4,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
  {
    id: 5,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
  {
    id: 6,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
  {
    id: 7,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
  {
    id: 8,
    image: imgAsus,
    title: "Asus ROG Zephyrus",
    description: "Laptop gaming",
    price: "129,999,000 ₫",
    vga: "RTX 3080Ti",
    cpu: "Ryzen 9 6900HX",
    display: "165Hz",
    ram: "32GB",
  },
];

export const fakeDataCompanyProduct = [
  {
    id: 1,
    image: imgAsus,
    title: "MACBOOK",
  },
  {
    id: 2,
    image: imgAsus,
    title: "DELL",
  },
  {
    id: 3,
    image: imgAsus,
    title: "ASUS",
  },
  {
    id: 4,
    image: imgAsus,
    title: "ACER",
  },
  {
    id: 5,
    image: imgAsus,
    title: "LENOVO",
  },
  {
    id: 6,
    image: imgAsus,
    title: "MSI",
  },
];
